#!/usr/bin/env bash
# 
# (c) Copyright 2021-present, SoftServe, Inc., All Rights Reserved.
#
set -e

openssl req -new -nodes -x509 -days 365 -keyout domain.key -out domain.crt -config ./certificate.config

# Verify certificate
openssl x509 -in domain.crt -noout -text | grep "IP Address:192.168.1.36"
