#!/usr/bin/env bash
# 
# (c) Copyright 2021-present, SoftServe, Inc., All Rights Reserved.
#
set -e

. $(git rev-parse --show-toplevel)/edgedevice/setup.env
export PATTERN_NAME="pattern-rpi4-pki"
hzn register --pattern "${HZN_ORG_ID}/${PATTERN_NAME}"