# 
# (c) Copyright 2021-present, SoftServe, Inc., All Rights Reserved.
#

FROM balenalib/raspberry-pi-debian:buster

# start rsyslog, FLEDGE, and tail syslog
CMD ["bash","echo 'overwrite key file'"]

LABEL maintainer="iot.test.0042@gmail.com" \
      author="Oleksandr Ivanov" \
      target="Docker" \
      version="${FLEDGE_VERSION}" \
      description="Fledge IoT Framework in Docker"
