#!/usr/bin/env bash
# 
# (c) Copyright 2021-present, SoftServe, Inc., All Rights Reserved.
#
set -e
. $(git rev-parse --show-toplevel)/workstation/setup.env

[ -z "$1" ] && (echo "Specify node name, i.e. $0 oh"; exit 1)
hzn exchange node liststatus $1