#!/usr/bin/env bash
# 
# (c) Copyright 2021-present, SoftServe, Inc., All Rights Reserved.
#
set -e

export SERVICE_VERSION=$(cat ../VERSION)
echo "Using version $SERVICE_VERSION..."

# Create builder
docker buildx ls | grep fledge_builder >/dev/null || docker buildx create --name fledge_builder

# Build arm image for RPi4
docker buildx use fledge_builder

pushd .

cd fledge_image
#docker buildx build . --platform linux/arm/v7 -t 192.168.1.36:5000/rpi4-fledge:$SERVICE_VERSION --load
docker buildx build . --platform linux/arm/v7 -t rpi4-fledge:$SERVICE_VERSION --load
#docker tag rpi4-fledge 192.168.1.36:5000/rpi4-fledge
docker tag rpi4-fledge:$SERVICE_VERSION 192.168.1.36:5000/rpi4-fledge:$SERVICE_VERSION

popd