#!/bin/sh
set -e
if [ -z "$1" ]; then
    SDK_NAME="automationhub/smartag-sdk"
fi
# Check parameters (only service)

# Build service as Docker image

# Publish policy

# TODO: use secret feature to run a secure image build --secret id=yoursecret,src=/host/secret/file/path
docker build \
    -t $SDK_NAME \
    .

# Publish SDK in your registry
#docker push automationhub/smartag-sdk:latest