#!/bin/sh
#!/usr/bin/env bash
set -e

. $PWD/support/functions
SMARTAG_EDGESERVER_IP=$(ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}')

eval export $(run_sdk get_server_env $SMARTAG_EDGESERVER_IP)

# Get latest docker-compose file to use for Edge Server
# docker-compose file is saved to /tmp/automationhub/docker-compose.yml
run_sdk gen_docker_compose

# Stop Edge Server
docker run \
    --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v "$PWD:$PWD" \
    -v "/tmp/automationhub:/tmp/automationhub" \
    -w="$PWD" \
    -it docker/compose:1.28.0 -f /tmp/automationhub/docker-compose.yml down
